export const amenities = [
    { name: "Kitchen", icon: "CookingPot" },
    { name: "Garden view", icon: "garden" },
    { name: "Pets allowed", icon: "pets" },
    { name: "Central air conditioning", icon: "ac" },
    { name: "Water heater", icon: "water" },
    { name: "Refrigerator", icon: "fridge" },
    { name: "Security cameras", icon: "security" },
    { name: "Boys Quarter", icon: "house" },
    { name: "Free Coffee", icon: "coffee" },
    { name: "Church Nearby", icon: "church" },
    { name: "Child Care", icon: "baby" },
    { name: "Fast Internet", icon: "wifi" },
    { name: "Big Compound", icon: "maximize" },
    { name: "24 Hours Electricity", icon: "zap" },
    { name: "Drainage System", icon: "pipette" },
    { name: "All Room Ensuite", icon: "door" },
    { name: "C of O", icon: "file" },
    { name: "Elevator", icon: "elevator" },
    { name: "Front Desk Service", icon: "bell" },
    { name: "24 Hours Security", icon: "shield" },
    { name: "CCTV Cameras", icon: "camera" },
    { name: "Children Play Ground", icon: "playground" },
    { name: "Swimming Pool", icon: "pool" },
    { name: "Survey", icon: "map" },
    { name: "Ocean View", icon: "waves" },
    { name: "POP Ceiling", icon: "ceiling" },
    { name: "Street Lights", icon: "lamp" },
    { name: "Office Supplies", icon: "briefcase" },
    { name: "Mosque Nearby", icon: "mosque" },
    { name: "Supermarket Nearby", icon: "shopping" },
    { name: "Governor's Consent", icon: "stamp" },
    { name: "Water Treatment", icon: "droplets" },
    { name: "Jacuzzi", icon: "hot-tub" },
    { name: "Printing Service", icon: "printer" },
    { name: "Security Doors", icon: "lock" },
    { name: "Restaurants Nearby", icon: "utensils" },
    { name: "Gym", icon: "dumbbell" },
    { name: "Parking Space", icon: "car" },
  ];