export const amenities = [
    { name: "Kitchen", icon: "CookingPot" },
    { name: "Pets allowed", icon: "pets" },
    { name: "Running Water", icon: "water" },
    { name: "Well Water", icon: "water" },
    { name: "Overhead Tank", icon: "water" },
    { name: "Separate Prepaid Meter", icon: "zap" },
    { name: "Security House", icon: "security" },
    { name: "Boys Quarter", icon: "house" },
    { name: "BQ", icon: "house" },
    { name: "Big Compound", icon: "maximize" },
    { name: "24 Hours Electricity", icon: "zap" },
    { name: "All Room Ensuite", icon: "door" },
    { name: "Wardrobe", icon: "door" },
    { name: "C of O", icon: "file" },
    { name: "Elevator", icon: "elevator" },
    { name: "24 Hours Security", icon: "shield" },
    { name: "CCTV Cameras", icon: "camera" },
    { name: "Swimming Pool", icon: "pool" },
    { name: "Survey", icon: "map" },
    { name: "POP Ceiling", icon: "ceiling" },
    { name: "Governor's Consent", icon: "stamp" },
    { name: "Jacuzzi", icon: "hot-tub" },
    { name: "Gym", icon: "dumbbell" },
    { name: "Parking Space", icon: "car" },
  ];
